# Generated by Django 5.2.6 on 2025-09-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completed",
        ),
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
